import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/app/components/styles/components-style.css"

import Navbar from '@/app/components/navbar'
import Sidebar from '@/app/components/sidebar'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <Navbar />
        <div className="flex">
          <div className="sidebar-wrap"><Sidebar /></div>
          <div className="container-main">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
